// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentHistory = `-- name: CreateDeploymentHistory :one
INSERT INTO deployment_histories (
  id, application_id, owner_user_id,
  repo_owner, repo_name,
  commit_sha, commit_message, commit_author, commit_at,
  pr_number, status, started_at
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12
) RETURNING id
`

type CreateDeploymentHistoryParams struct {
	ID            string
	ApplicationID string
	OwnerUserID   string
	RepoOwner     string
	RepoName      string
	CommitSha     string
	CommitMessage string
	CommitAuthor  string
	CommitAt      pgtype.Timestamptz
	PrNumber      *int32
	Status        string
	StartedAt     pgtype.Timestamptz
}

func (q *Queries) CreateDeploymentHistory(ctx context.Context, arg CreateDeploymentHistoryParams) (string, error) {
	row := q.db.QueryRow(ctx, createDeploymentHistory,
		arg.ID,
		arg.ApplicationID,
		arg.OwnerUserID,
		arg.RepoOwner,
		arg.RepoName,
		arg.CommitSha,
		arg.CommitMessage,
		arg.CommitAuthor,
		arg.CommitAt,
		arg.PrNumber,
		arg.Status,
		arg.StartedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteDeploymentHistory = `-- name: DeleteDeploymentHistory :exec
DELETE FROM deployment_histories WHERE id = $1
`

func (q *Queries) DeleteDeploymentHistory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDeploymentHistory, id)
	return err
}

const getDeploymentHistory = `-- name: GetDeploymentHistory :one
SELECT id, application_id, owner_user_id, repo_owner, repo_name, commit_sha, commit_message, commit_author, commit_at, pr_number, status, started_at, finished_at FROM deployment_histories WHERE id = $1
`

func (q *Queries) GetDeploymentHistory(ctx context.Context, id string) (DeploymentHistory, error) {
	row := q.db.QueryRow(ctx, getDeploymentHistory, id)
	var i DeploymentHistory
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OwnerUserID,
		&i.RepoOwner,
		&i.RepoName,
		&i.CommitSha,
		&i.CommitMessage,
		&i.CommitAuthor,
		&i.CommitAt,
		&i.PrNumber,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeploymentHistoriesByApplication = `-- name: ListDeploymentHistoriesByApplication :many
SELECT id, application_id, owner_user_id, repo_owner, repo_name, commit_sha, commit_message, commit_author, commit_at, pr_number, status, started_at, finished_at FROM deployment_histories
WHERE application_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListDeploymentHistoriesByApplication(ctx context.Context, applicationID string) ([]DeploymentHistory, error) {
	rows, err := q.db.Query(ctx, listDeploymentHistoriesByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentHistory
	for rows.Next() {
		var i DeploymentHistory
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.OwnerUserID,
			&i.RepoOwner,
			&i.RepoName,
			&i.CommitSha,
			&i.CommitMessage,
			&i.CommitAuthor,
			&i.CommitAt,
			&i.PrNumber,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentHistoryStatus = `-- name: UpdateDeploymentHistoryStatus :exec
UPDATE deployment_histories
SET status = $2, finished_at = $3
WHERE id = $1
`

type UpdateDeploymentHistoryStatusParams struct {
	ID         string
	Status     string
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) UpdateDeploymentHistoryStatus(ctx context.Context, arg UpdateDeploymentHistoryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentHistoryStatus, arg.ID, arg.Status, arg.FinishedAt)
	return err
}
