// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_role.sql

package db

import (
	"context"
)

const addProjectGroupRole = `-- name: AddProjectGroupRole :one
INSERT INTO project_group_roles (id, project_id, oidc_role, role, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, oidc_role, role, created_at, created_by
`

type AddProjectGroupRoleParams struct {
	ID        string
	ProjectID string
	OidcRole  string
	Role      string
	CreatedBy string
}

func (q *Queries) AddProjectGroupRole(ctx context.Context, arg AddProjectGroupRoleParams) (ProjectGroupRole, error) {
	row := q.db.QueryRow(ctx, addProjectGroupRole,
		arg.ID,
		arg.ProjectID,
		arg.OidcRole,
		arg.Role,
		arg.CreatedBy,
	)
	var i ProjectGroupRole
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OidcRole,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listProjectGroupRoles = `-- name: ListProjectGroupRoles :many
SELECT id, project_id, oidc_role, role, created_at, created_by FROM project_group_roles WHERE project_id = $1
`

func (q *Queries) ListProjectGroupRoles(ctx context.Context, projectID string) ([]ProjectGroupRole, error) {
	rows, err := q.db.Query(ctx, listProjectGroupRoles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGroupRole
	for rows.Next() {
		var i ProjectGroupRole
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OidcRole,
			&i.Role,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectGroupRolesByGroups = `-- name: ListProjectGroupRolesByGroups :many
SELECT id, project_id, oidc_role, role, created_at, created_by FROM project_group_roles WHERE project_id = $1 AND oidc_role = ANY($2::text[])
`

type ListProjectGroupRolesByGroupsParams struct {
	ProjectID string
	OidcRoles []string
}

func (q *Queries) ListProjectGroupRolesByGroups(ctx context.Context, arg ListProjectGroupRolesByGroupsParams) ([]ProjectGroupRole, error) {
	rows, err := q.db.Query(ctx, listProjectGroupRolesByGroups, arg.ProjectID, arg.OidcRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGroupRole
	for rows.Next() {
		var i ProjectGroupRole
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OidcRole,
			&i.Role,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectGroupRole = `-- name: RemoveProjectGroupRole :exec
DELETE FROM project_group_roles WHERE id = $1
`

func (q *Queries) RemoveProjectGroupRole(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeProjectGroupRole, id)
	return err
}

const updateProjectGroupRoleRole = `-- name: UpdateProjectGroupRoleRole :exec
UPDATE project_group_roles SET role = $2 WHERE id = $1
`

type UpdateProjectGroupRoleRoleParams struct {
	ID   string
	Role string
}

func (q *Queries) UpdateProjectGroupRoleRole(ctx context.Context, arg UpdateProjectGroupRoleRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectGroupRoleRole, arg.ID, arg.Role)
	return err
}
