// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (id, project_id, user_id, role, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, user_id, role, created_at, created_by
`

type AddProjectMemberParams struct {
	ID        string
	ProjectID string
	UserID    string
	Role      string
	CreatedBy string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedBy,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, project_id, user_id, role, created_at, created_by FROM project_members WHERE project_id = $1 AND user_id = $2 LIMIT 1
`

type GetProjectMemberParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT id, project_id, user_id, role, created_at, created_by FROM project_members WHERE project_id = $1
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE id = $1
`

func (q *Queries) RemoveProjectMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeProjectMember, id)
	return err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members SET role = $2 WHERE id = $1
`

type UpdateProjectMemberRoleParams struct {
	ID   string
	Role string
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.ID, arg.Role)
	return err
}
