// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentHistory struct {
	ID            string
	ApplicationID string
	OwnerUserID   string
	RepoOwner     string
	RepoName      string
	CommitSha     string
	CommitMessage string
	CommitAuthor  string
	CommitAt      pgtype.Timestamptz
	PrNumber      *int32
	Status        string
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type User struct {
	ID          string
	DisplayID   string
	DisplayName string
	Roles       []string
	CreatedAt   pgtype.Timestamptz
}
