// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_id, display_name, roles, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayID,
		&i.DisplayName,
		&i.Roles,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, display_id, display_name, roles)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
  SET display_id   = EXCLUDED.display_id,
      display_name = EXCLUDED.display_name,
      roles        = EXCLUDED.roles
RETURNING id, display_id, display_name, roles, created_at
`

type UpsertUserParams struct {
	ID          string
	DisplayID   string
	DisplayName string
	Roles       []string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.DisplayID,
		arg.DisplayName,
		arg.Roles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayID,
		&i.DisplayName,
		&i.Roles,
		&i.CreatedAt,
	)
	return i, err
}
