syntax = "proto3";

package maxicloud.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

enum DeploymentStatus {
  DEPLOYMENT_STATUS_UNSPECIFIED = 0;
  DEPLOYMENT_STATUS_SUCCESS = 1;
  DEPLOYMENT_STATUS_IN_PROGRESS = 2;
  DEPLOYMENT_STATUS_FAILED = 3;
}

message Commit {
  string sha = 1;
  string message = 2;
  string author_name = 3;
  google.protobuf.Timestamp timestamp = 4;
}

message Deployment {
  string id = 1;
  string application_id = 2;
  string owner_user_id = 3;
  Commit commit = 4;
  DeploymentStatus status = 5;
  google.protobuf.Timestamp started_at = 6;
  optional google.protobuf.Timestamp finished_at = 7;
}

message RetryDeploymentRequest {
  string deployment_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message RetryDeploymentResponse {
  Deployment deployment = 1;
}

message GetDeploymentRequest {
  string deployment_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message GetDeploymentResponse {
  Deployment deployment = 1;
}

message ListDeploymentsRequest {
  string application_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message ListDeploymentsResponse {
  repeated Deployment deployments = 1;
}

message WatchDeploymentRequest {
  string deployment_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message WatchDeploymentResponse {
  oneof event {
    DeploymentStatusChangedEvent deployment_status_changed = 1;
    DeploymentLogChunkEvent deployment_log_chunk = 2;
  }
}

message DeploymentStatusChangedEvent {
  DeploymentStatus status = 1;
  int64 elapsed_seconds = 2;
  optional google.protobuf.Timestamp finished_at = 3;
}

message DeploymentLogChunkEvent {
  string line = 1;
}

service DeploymentService {
  rpc RetryDeployment(RetryDeploymentRequest) returns (RetryDeploymentResponse);
  rpc GetDeployment(GetDeploymentRequest) returns (GetDeploymentResponse);
  rpc ListDeployments(ListDeploymentsRequest) returns (ListDeploymentsResponse);
  rpc WatchDeployment(WatchDeploymentRequest) returns (stream WatchDeploymentResponse);
}
