# This rule is not used by the project maxicloud itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over maxicloud.maximum.vc.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: maxicloud
    app.kubernetes.io/managed-by: kustomize
  name: deployrun-admin-role
rules:
- apiGroups:
  - maxicloud.maximum.vc
  resources:
  - deployruns
  verbs:
  - '*'
- apiGroups:
  - maxicloud.maximum.vc
  resources:
  - deployruns/status
  verbs:
  - get
