name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-lint:
    name: Backend lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0

      - name: Build custom golangci-lint
        run: mise run go:lint-setup

      - name: Run linter
        run: mise run go:lint

  frontend-lint:
    name: Frontend lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        working-directory: dashboard

      - name: Run frontend check
        run: mise run ts:lint
