name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install tools
        run: GOBIN="$(pwd)/bin" go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.20.1

      - name: Install dashboard dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        working-directory: dashboard

      - name: Run tests
        run: mise run test
